services:
  qda_api:
    build:
      context: ./backend
    environment:
      - LOG_LEVEL=INFO
      - DATA_DIR=/app/data
    container_name: qda_api
    restart: unless-stopped
    ports:
      - "8011:8000"
    volumes:
      - ./data:/app/data
      - ./out:/app/out
      - ./config:/app/config
    depends_on:
      qda_worker:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - qda_network

  qda_worker:
    build:
      context: ./worker
    container_name: qda_worker
    restart: unless-stopped
    ports:
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - LOG_LEVEL=INFO
      - HF_HOME=/cache/huggingface
      - SENT_HOME=/cache/german_sentiment
      - TORCH_HOME=/cache/torch
      - SENTENCE_TRANSFORMERS_HOME=/cache/sentence_transformers
      - SPACY_DATA=/cache/spacy
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

    volumes:
      - ./data:/app/data
      - ./out:/app/out
      - ./config:/app/config
      - ./worker:/app
      - ./cache:/cache
    networks:
      - qda_network

networks:
  qda_network:
    driver: bridge
